#Backend Bucket Variabes
variable "region" {}
variable "iam_user_name" {}
variable "bucket_name" {}
variable "table_name" {}
variable "root_domain" {}
variable "dns_record_ttl" {}
variable "website_bucket" {}
variable "bucket_regional_domain_name" {}
variable "s3_bucket_id" {}
variable "ssl_cert_arn" {}
variable "route53_zone_id" {}
