name: Deploy Website

on:
  push:
    branches: -main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

  env:
    AWS_ACCESS_KEY_ID: ${{ secrets. AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ }}

  defaults:
    run:
    working-directory: ./terraform

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
